# Generated by Django 5.1.7 on 2025-03-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatomoSite',
            fields=[
                ('site_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('visits', models.IntegerField()),
                ('pageviews', models.IntegerField()),
                ('bounce_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.matomosite')),
            ],
        ),
    ]
